In [1]:
import pandas as pd

In [2]:
kali_ppt_list1 = pd.read_excel('kali_ppt_list1.xlsx')
parameter_each_site = pd.read_excel('parameter_each_site.xlsx')

In [3]:
kali_ppt_list1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 27 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   S_N_        40 non-null     int64
 1   Station_na  40 non-null     object
 2   Index_No_   40 non-null     int64
 3   Basin_Offi  40 non-null     object
 4   Type_of_st  40 non-null     object
 5   District    40 non-null     object
 6   F7          40 non-null     int64
 7   F8          40 non-null     int64
 8   F9          40 non-null     int64
 9   Latitude    40 non-null     float64
 10  F11         40 non-null     int64
 11  F12         40 non-null     int64
 12  F13         40 non-null     int64
 13  Longitude   40 non-null     float64
 14  F15         40 non-null     int64
 15  F16         14 non-null     object
 16  F17         31 non-null     object
 17  F18         40 non-null     int64
 18  F19         2 non-null      object
 19  F20         0 non-null      float64
 20  F21         11 non-null     object
 21  F22         0 non-null      float64
 22  F23         0 non-null      float64
 23  PPT         40 non-null     float64
 24  Tmax        40 non-null     int64
 25  Tmin        40 non-null     int64
 26  D_C_245     40 non-null     int64
dtypes: float64(6), int64(13), object(8)
memory usage: 8.6+ KB

In [4]:
parameter_each_site.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        0 non-null      float64
 1   Parameter Name    29 non-null     object
 2   Suggested Range   29 non-null     object
 3   Unnamed: 3        0 non-null      float64
 4   Kaligandaki       30 non-null     object
 5   Unnamed: 5        30 non-null     object
 6   Unnamed: 6        30 non-null     object
 7   Unnamed: 7        0 non-null      float64
 8   Seti Gandaki      30 non-null     object
 9   Unnamed: 9        0 non-null      float64
 10  Marshyangdi       30 non-null     object
 11  Unnamed: 11       0 non-null      float64
 12  Budhigandaki      30 non-null     object
 13  Unnamed: 13       0 non-null      float64
 14  Trishuli          30 non-null     object
 15  Unnamed: 15       30 non-null     object
 16  Unnamed: 16       30 non-null     object
 17  Unnamed: 17       0 non-null      float64
 18  Narayani          30 non-null     object
dtypes: float64(7), object(12)
memory usage: 4.6+ KB

In [5]:
kali_ppt_list1.head()

,S_N_,Station_na,Index_No_,Basin_Offi,Type_of_st,District,F7,F8,F9,Latitude,...,F18,F19,F20,F21,F22,F23,PPT,Tmax,Tmin,D_C_245
0,72,JOMSOM,601,N,CLIMATOLOGY,Mustang,2847,28,47,28.783333,...,72,I JAN 71,NaN,JUN 78E,NaN,NaN,286.2,0,0,0
1,73,THAKMARPHA,604,N,AGROMETEOROLOGY,Mustang,2845,28,45,28.750000,...,66,NaN,NaN,NaN,NaN,NaN,435.9,0,0,0
2,74,BAGLUNG,605,N,CLIMATOLOGY,Baglung,2816,28,16,28.266667,...,69,NaN,NaN,NOV 78E,NaN,NaN,2074.9,0,0,0
3,75,TATOPANI,606,N,PRECIPITATION,Myagdi,2829,28,29,28.483333,...,69,NaN,NaN,NaN,NaN,NaN,1652.5,0,0,0
4,76,LETE,607,N,CLIMATOLOGY,Mustang,2838,28,38,28.633333,...,69,NaN,NaN,MAY 98E,NaN,NaN,1660.5,0,0,0

In [6]:
df = kali_ppt_list1[['S_N_', 'Index_No_', 'Latitude', 'Longitude', 'F15']]
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   S_N_       40 non-null     int64
 1   Index_No_  40 non-null     int64
 2   Latitude   40 non-null     float64
 3   Longitude  40 non-null     float64
 4   F15        40 non-null     int64
dtypes: float64(2), int64(3)
memory usage: 1.7 KB

In [7]:
index_no_values = [601, 604, 605, 606, 715, 805, 810, 814]

final_df = df[df['Index_No_'].isin(index_no_values)]

final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8 entries, 0 to 33
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   S_N_       8 non-null      int64
 1   Index_No_  8 non-null      int64
 2   Latitude   8 non-null      float64
 3   Longitude  8 non-null      float64
 4   F15        8 non-null      int64
dtypes: float64(2), int64(3)
memory usage: 384.0 bytes

In [8]:
final_df

    S_N_  Index_No_   Latitude  Longitude   F15
0     72        601  28.783333  83.716667  2744
1     73        604  28.750000  83.700000  2566
2     74        605  28.266667  83.600000   984
3     75        606  28.483333  83.650000  1243
26   107        715  27.933333  83.150000  1760
30   120        805  28.100000  83.883333   868
31   125        810  27.883333  83.816667   460
33   128        814  28.300000  83.800000  1740

In [9]:
final_df.drop(columns=['S_N_'], inplace=True)
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8 entries, 0 to 33
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Index_No_  8 non-null      int64
 1   Latitude   8 non-null      float64
 2   Longitude  8 non-null      float64
 3   F15        8 non-null      int64
dtypes: float64(2), int64(2)
memory usage: 320.0 bytes

C:\Users\Gunjan M\AppData\Local\Temp\ipykernel_11480\4293167149.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df.drop(columns=['S_N_'], inplace=True)

In [10]:
final_df.head()

    Index_No_   Latitude  Longitude   F15
0         601  28.783333  83.716667  2744
1         604  28.750000  83.700000  2566
2         605  28.266667  83.600000   984
3         606  28.483333  83.650000  1243
26        715  27.933333  83.150000  1760

In [39]:
final_df = final_df.rename(columns={'F15': 'Elevation'})
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8 entries, 0 to 33
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Index_No_  8 non-null      int64
 1   Latitude   8 non-null      float64
 2   Longitude  8 non-null      float64
 3   Elevation  8 non-null      int64
dtypes: float64(2), int64(2)
memory usage: 320.0 bytes

In [40]:
static_data = final_df
static_data.to_csv('static_data.csv')

In [14]:
tmax = pd.read_csv('Tmax.csv')
tmin = pd.read_csv('tmin.csv')

In [15]:
print(tmax.info())
print(tmin.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14976 entries, 0 to 14975
Data columns (total 19 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Date     14976 non-null  object
 1   ST_601   14976 non-null  float64
 2   ST_604   14976 non-null  float64
 3   ST_605   14976 non-null  object
 4   ST_706   14976 non-null  float64
 5   ST_715   14976 non-null  float64
 6   ST_802   14976 non-null  float64
 7   ST_804   14976 non-null  float64
 8   ST_805   14976 non-null  float64
 9   ST_809   14976 non-null  float64
 10  ST_810   14976 non-null  float64
 11  ST_811   14976 non-null  float64
 12  ST_814   14976 non-null  float64
 13  ST_815   14976 non-null  float64
 14  ST_816   14976 non-null  float64
 15  ST_902   14976 non-null  float64
 16  ST_906   14976 non-null  float64
 17  ST_1007  14976 non-null  object
 18  ST_1038  14976 non-null  float64
dtypes: float64(16), object(3)
memory usage: 2.2+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14976 entries, 0 to 14975
Data columns (total 19 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Date     14976 non-null  object
 1   ST_601   14976 non-null  float64
 2   ST_604   14976 non-null  float64
 3   ST_605   14976 non-null  float64
 4   ST_706   14976 non-null  float64
 5   ST_715   14976 non-null  float64
 6   ST_802   14976 non-null  float64
 7   ST_804   14976 non-null  float64
 8   ST_805   14976 non-null  float64
 9   ST_809   14976 non-null  float64
 10  ST_810   14976 non-null  float64
 11  ST_811   14976 non-null  float64
 12  ST_814   14976 non-null  float64
 13  ST_815   14976 non-null  float64
 14  ST_816   14976 non-null  float64
 15  ST_902   14976 non-null  float64
 16  ST_906   14976 non-null  float64
 17  ST_1007  14976 non-null  float64
 18  ST_1038  14976 non-null  float64
dtypes: float64(18), object(1)
memory usage: 2.2+ MB
None

In [17]:
merged_df = pd.merge(tmax, tmin, on='Date', suffixes=('_tmax', '_tmin'))

# Display the merged dataframe
print(merged_df)

             Date  ST_601_tmax  ST_604_tmax ST_605_tmax  ST_706_tmax  \
0        1/1/1980        11.31          9.2       13.00         21.1
1        1/2/1980        11.39          9.2       19.00         22.8
2        1/3/1980        11.54          7.8       19.80         22.2
3        1/4/1980        11.45          8.3       19.60         22.2
4        1/5/1980        10.96         10.2       19.40         21.6
...           ...          ...          ...         ...          ...
14971  12/27/2020        11.50         14.0       21.20         25.8
14972  12/28/2020        12.00         12.0       21.00         27.0
14973  12/29/2020        13.50         14.5       21.20         25.8
14974  12/30/2020        11.80         12.5       20.10         25.0
14975  12/31/2020        13.30         16.0       20.20         27.0

       ST_715_tmax  ST_802_tmax  ST_804_tmax  ST_805_tmax  ST_809_tmax  ...  \
0             14.0         16.0         13.0         19.0        11.20  ...
1             11.7         17.4         17.0         18.6        15.00  ...
2             11.4         17.8         17.0         20.4        15.50  ...
3             12.5         17.2         17.2         18.8        16.60  ...
4             12.8         17.2         17.4         20.0        15.60  ...
...            ...          ...          ...          ...          ...  ...
14971         17.0         22.3         20.2         18.6        19.69  ...
14972         17.0         20.9         20.6         18.7        19.61  ...
14973         15.5         21.3         20.2         18.0        19.59  ...
14974         18.4         20.5         20.0         18.7        19.78  ...
14975         18.0         21.6         20.3         17.0        19.63  ...

       ST_809_tmin  ST_810_tmin  ST_811_tmin  ST_814_tmin  ST_815_tmin  \
0           6.8000          8.4          4.8       4.0000          8.2
1           7.4000          9.0          4.2       4.9000          8.0
2           8.0000         10.0          3.5       4.0000          8.0
3           7.6000          9.0          4.5       3.5000          9.1
4           7.5000          7.0          3.5       3.0000          8.2
...            ...          ...          ...          ...          ...
14971       6.4027          7.2          5.0       7.9978          9.0
14972       6.4757          8.0          4.5       7.8127          8.5
14973       6.6865          7.9          3.8       8.0506          8.4
14974       6.7243          7.6          3.8       7.8084          4.5
14975       6.5081          6.6          2.7       8.3360          4.7

       ST_816_tmin  ST_902_tmin ST_906_tmin  ST_1007_tmin  ST_1038_tmin
0          -8.1000          8.2        3.00       -4.9000        6.5000
1         -10.1000          9.3       10.00       -1.2000        7.0000
2          -6.1000          8.2        7.49       -2.0000        7.0000
3          -7.4000          8.2        6.00       -1.2000        6.5000
4          -8.3000          5.2        4.50       -1.5000        6.0000
...            ...          ...         ...           ...           ...
14971       5.0184          7.0        6.10        7.7865        7.1895
14972       5.1579          7.2        7.40        7.9081        7.4632
14973       5.2263          5.6        6.90        7.8027        7.2132
14974       5.2500          5.7        6.40        8.0541        7.2000
14975       4.8605          4.2        5.90        8.0278        7.5541

[14976 rows x 37 columns]

In [19]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14976 entries, 0 to 14975
Data columns (total 37 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          14976 non-null  object
 1   ST_601_tmax   14976 non-null  float64
 2   ST_604_tmax   14976 non-null  float64
 3   ST_605_tmax   14976 non-null  object
 4   ST_706_tmax   14976 non-null  float64
 5   ST_715_tmax   14976 non-null  float64
 6   ST_802_tmax   14976 non-null  float64
 7   ST_804_tmax   14976 non-null  float64
 8   ST_805_tmax   14976 non-null  float64
 9   ST_809_tmax   14976 non-null  float64
 10  ST_810_tmax   14976 non-null  float64
 11  ST_811_tmax   14976 non-null  float64
 12  ST_814_tmax   14976 non-null  float64
 13  ST_815_tmax   14976 non-null  float64
 14  ST_816_tmax   14976 non-null  float64
 15  ST_902_tmax   14976 non-null  float64
 16  ST_906_tmax   14976 non-null  float64
 17  ST_1007_tmax  14976 non-null  object
 18  ST_1038_tmax  14976 non-null  float64
 19  ST_601_tmin   14976 non-null  float64
 20  ST_604_tmin   14976 non-null  float64
 21  ST_605_tmin   14976 non-null  float64
 22  ST_706_tmin   14976 non-null  float64
 23  ST_715_tmin   14976 non-null  float64
 24  ST_802_tmin   14976 non-null  float64
 25  ST_804_tmin   14976 non-null  float64
 26  ST_805_tmin   14976 non-null  float64
 27  ST_809_tmin   14976 non-null  float64
 28  ST_810_tmin   14976 non-null  float64
 29  ST_811_tmin   14976 non-null  float64
 30  ST_814_tmin   14976 non-null  float64
 31  ST_815_tmin   14976 non-null  float64
 32  ST_816_tmin   14976 non-null  float64
 33  ST_902_tmin   14976 non-null  float64
 34  ST_906_tmin   14976 non-null  float64
 35  ST_1007_tmin  14976 non-null  float64
 36  ST_1038_tmin  14976 non-null  float64
dtypes: float64(34), object(3)
memory usage: 4.2+ MB

In [20]:
merged_df.head()

,Date,ST_601_tmax,ST_604_tmax,ST_605_tmax,ST_706_tmax,ST_715_tmax,ST_802_tmax,ST_804_tmax,ST_805_tmax,ST_809_tmax,...,ST_809_tmin,ST_810_tmin,ST_811_tmin,ST_814_tmin,ST_815_tmin,ST_816_tmin,ST_902_tmin,ST_906_tmin,ST_1007_tmin,ST_1038_tmin
0,1/1/1980,11.31,9.2,13.00,21.1,14.0,16.0,13.0,19.0,11.2,...,6.8,8.4,4.8,4.0,8.2,-8.1,8.2,3.00,-4.9,6.5
1,1/2/1980,11.39,9.2,19.00,22.8,11.7,17.4,17.0,18.6,15.0,...,7.4,9.0,4.2,4.9,8.0,-10.1,9.3,10.00,-1.2,7.0
2,1/3/1980,11.54,7.8,19.80,22.2,11.4,17.8,17.0,20.4,15.5,...,8.0,10.0,3.5,4.0,8.0,-6.1,8.2,7.49,-2.0,7.0
3,1/4/1980,11.45,8.3,19.60,22.2,12.5,17.2,17.2,18.8,16.6,...,7.6,9.0,4.5,3.5,9.1,-7.4,8.2,6.00,-1.2,6.5
4,1/5/1980,10.96,10.2,19.40,21.6,12.8,17.2,17.4,20.0,15.6,...,7.5,7.0,3.5,3.0,8.2,-8.3,5.2,4.50,-1.5,6.0

In [22]:
# List to store valid columns (where both Tmax and Tmin exist)
valid_columns = ['Date']  # Always keep the Date column

# Check for each station if both Tmax and Tmin columns exist
for station in index_no_values:
    tmax_col = f'ST_{station}_tmax'
    tmin_col = f'ST_{station}_tmin'
    
    # Only include the station if both Tmax and Tmin columns exist
    if tmax_col in merged_df.columns and tmin_col in merged_df.columns:
        valid_columns.append(tmax_col)
        valid_columns.append(tmin_col)

# Filter the dataframe to only keep valid columns
filtered_df = merged_df[valid_columns]

In [23]:
filtered_df.head()

,Date,ST_601_tmax,ST_601_tmin,ST_604_tmax,ST_604_tmin,ST_605_tmax,ST_605_tmin,ST_715_tmax,ST_715_tmin,ST_805_tmax,ST_805_tmin,ST_810_tmax,ST_810_tmin,ST_814_tmax,ST_814_tmin
0,1/1/1980,11.31,-1.95,9.2,-3.0,13.00,5.6,14.0,4.3,19.0,6.02,16.0,8.4,13.0,4.0
1,1/2/1980,11.39,-1.74,9.2,-2.0,19.00,7.8,11.7,4.0,18.6,5.40,16.0,9.0,11.2,4.9
2,1/3/1980,11.54,-2.21,7.8,-5.0,19.80,5.4,11.4,5.2,20.4,5.00,18.4,10.0,12.9,4.0
3,1/4/1980,11.45,-2.51,8.3,-5.0,19.60,5.0,12.5,3.3,18.8,6.20,20.2,9.0,10.9,3.5
4,1/5/1980,10.96,-2.32,10.2,-4.2,19.40,4.6,12.8,3.6,20.0,4.80,19.0,7.0,11.5,3.0

In [24]:
filtered_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14976 entries, 0 to 14975
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         14976 non-null  object
 1   ST_601_tmax  14976 non-null  float64
 2   ST_601_tmin  14976 non-null  float64
 3   ST_604_tmax  14976 non-null  float64
 4   ST_604_tmin  14976 non-null  float64
 5   ST_605_tmax  14976 non-null  object
 6   ST_605_tmin  14976 non-null  float64
 7   ST_715_tmax  14976 non-null  float64
 8   ST_715_tmin  14976 non-null  float64
 9   ST_805_tmax  14976 non-null  float64
 10  ST_805_tmin  14976 non-null  float64
 11  ST_810_tmax  14976 non-null  float64
 12  ST_810_tmin  14976 non-null  float64
 13  ST_814_tmax  14976 non-null  float64
 14  ST_814_tmin  14976 non-null  float64
dtypes: float64(13), object(2)
memory usage: 1.7+ MB

In [25]:
t_filtered = filtered_df
t_filtered.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14976 entries, 0 to 14975
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         14976 non-null  object
 1   ST_601_tmax  14976 non-null  float64
 2   ST_601_tmin  14976 non-null  float64
 3   ST_604_tmax  14976 non-null  float64
 4   ST_604_tmin  14976 non-null  float64
 5   ST_605_tmax  14976 non-null  object
 6   ST_605_tmin  14976 non-null  float64
 7   ST_715_tmax  14976 non-null  float64
 8   ST_715_tmin  14976 non-null  float64
 9   ST_805_tmax  14976 non-null  float64
 10  ST_805_tmin  14976 non-null  float64
 11  ST_810_tmax  14976 non-null  float64
 12  ST_810_tmin  14976 non-null  float64
 13  ST_814_tmax  14976 non-null  float64
 14  ST_814_tmin  14976 non-null  float64
dtypes: float64(13), object(2)
memory usage: 1.7+ MB

In [26]:
ppt = pd.read_csv('ppt.csv')
ppt.head()

,Date,st601,st604,st605,st606,st607,st608,st609,st610,st612,...,st1004,st1005,st1007,st1038,st1054,st1054.1,st1055,st1057,st1079,Unnamed: 80
0,1/1/1980,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,NaN
1,1/2/1980,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,NaN
2,1/3/1980,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,NaN
3,1/4/1980,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,NaN
4,1/5/1980,0.0,0.0,13.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,NaN

In [27]:
ppt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14976 entries, 0 to 14975
Data columns (total 81 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         14976 non-null  object
 1   st601        14976 non-null  float64
 2   st604        14976 non-null  float64
 3   st605        14976 non-null  float64
 4   st606        14976 non-null  float64
 5   st607        14976 non-null  float64
 6   st608        14976 non-null  float64
 7   st609        14976 non-null  float64
 8   st610        14976 non-null  float64
 9   st612        14976 non-null  float64
 10  st613        14976 non-null  float64
 11  st614        14976 non-null  float64
 12  st615        14976 non-null  float64
 13  st616        14976 non-null  float64
 14  st619        14976 non-null  float64
 15  st620        14976 non-null  float64
 16  st621        14976 non-null  float64
 17  st622        14976 non-null  float64
 18  st624        14976 non-null  float64
 19  st625        14976 non-null  float64
 20  st626        14976 non-null  float64
 21  st627        14976 non-null  float64
 22  st628        14976 non-null  float64
 23  st629        14976 non-null  float64
 24  st630        14976 non-null  float64
 25  st633        14976 non-null  float64
 26  st701        14976 non-null  float64
 27  st704        14976 non-null  float64
 28  st706        14945 non-null  float64
 29  st710        14976 non-null  float64
 30  st715        14976 non-null  float64
 31  st722        14976 non-null  float64
 32  st725        14976 non-null  float64
 33  st726        14976 non-null  float64
 34  st801        14976 non-null  float64
 35  st802        14976 non-null  float64
 36  st804        14976 non-null  float64
 37  st805        14976 non-null  float64
 38  st806        14976 non-null  float64
 39  st807        14976 non-null  float64
 40  st808        14976 non-null  float64
 41  st809        14976 non-null  float64
 42  st810        14976 non-null  float64
 43  st811        14976 non-null  float64
 44  st813        14976 non-null  float64
 45  st814        14976 non-null  float64
 46  st815        14976 non-null  float64
 47  st816        14976 non-null  float64
 48  st817        14976 non-null  float64
 49  st818        14976 non-null  float64
 50  st820        14976 non-null  float64
 51  st821        14976 non-null  float64
 52  st823        14976 non-null  float64
 53  st824        14976 non-null  float64
 54  st826        14976 non-null  float64
 55  st827        14976 non-null  float64
 56  st829        14976 non-null  float64
 57  st830        14976 non-null  float64
 58  st832        14976 non-null  float64
 59  st833        14976 non-null  float64
 60  st834        14976 non-null  float64
 61  st866        14976 non-null  float64
 62  st902        14976 non-null  float64
 63  st903        14976 non-null  float64
 64  st904        14976 non-null  float64
 65  st906        14976 non-null  float64
 66  st919        14976 non-null  float64
 67  st920        14976 non-null  float64
 68  st925        14976 non-null  float64
 69  st927        14976 non-null  float64
 70  st1002       14976 non-null  float64
 71  st1004       14976 non-null  float64
 72  st1005       14976 non-null  float64
 73  st1007       14976 non-null  float64
 74  st1038       14976 non-null  float64
 75  st1054       14976 non-null  float64
 76  st1054.1     13880 non-null  float64
 77  st1055       14976 non-null  float64
 78  st1057       14976 non-null  float64
 79  st1079       14976 non-null  float64
 80  Unnamed: 80  13149 non-null  float64
dtypes: float64(80), object(1)
memory usage: 9.3+ MB

In [28]:
ppt = ppt.iloc[:, :-1]

In [29]:
ppt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14976 entries, 0 to 14975
Data columns (total 80 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      14976 non-null  object
 1   st601     14976 non-null  float64
 2   st604     14976 non-null  float64
 3   st605     14976 non-null  float64
 4   st606     14976 non-null  float64
 5   st607     14976 non-null  float64
 6   st608     14976 non-null  float64
 7   st609     14976 non-null  float64
 8   st610     14976 non-null  float64
 9   st612     14976 non-null  float64
 10  st613     14976 non-null  float64
 11  st614     14976 non-null  float64
 12  st615     14976 non-null  float64
 13  st616     14976 non-null  float64
 14  st619     14976 non-null  float64
 15  st620     14976 non-null  float64
 16  st621     14976 non-null  float64
 17  st622     14976 non-null  float64
 18  st624     14976 non-null  float64
 19  st625     14976 non-null  float64
 20  st626     14976 non-null  float64
 21  st627     14976 non-null  float64
 22  st628     14976 non-null  float64
 23  st629     14976 non-null  float64
 24  st630     14976 non-null  float64
 25  st633     14976 non-null  float64
 26  st701     14976 non-null  float64
 27  st704     14976 non-null  float64
 28  st706     14945 non-null  float64
 29  st710     14976 non-null  float64
 30  st715     14976 non-null  float64
 31  st722     14976 non-null  float64
 32  st725     14976 non-null  float64
 33  st726     14976 non-null  float64
 34  st801     14976 non-null  float64
 35  st802     14976 non-null  float64
 36  st804     14976 non-null  float64
 37  st805     14976 non-null  float64
 38  st806     14976 non-null  float64
 39  st807     14976 non-null  float64
 40  st808     14976 non-null  float64
 41  st809     14976 non-null  float64
 42  st810     14976 non-null  float64
 43  st811     14976 non-null  float64
 44  st813     14976 non-null  float64
 45  st814     14976 non-null  float64
 46  st815     14976 non-null  float64
 47  st816     14976 non-null  float64
 48  st817     14976 non-null  float64
 49  st818     14976 non-null  float64
 50  st820     14976 non-null  float64
 51  st821     14976 non-null  float64
 52  st823     14976 non-null  float64
 53  st824     14976 non-null  float64
 54  st826     14976 non-null  float64
 55  st827     14976 non-null  float64
 56  st829     14976 non-null  float64
 57  st830     14976 non-null  float64
 58  st832     14976 non-null  float64
 59  st833     14976 non-null  float64
 60  st834     14976 non-null  float64
 61  st866     14976 non-null  float64
 62  st902     14976 non-null  float64
 63  st903     14976 non-null  float64
 64  st904     14976 non-null  float64
 65  st906     14976 non-null  float64
 66  st919     14976 non-null  float64
 67  st920     14976 non-null  float64
 68  st925     14976 non-null  float64
 69  st927     14976 non-null  float64
 70  st1002    14976 non-null  float64
 71  st1004    14976 non-null  float64
 72  st1005    14976 non-null  float64
 73  st1007    14976 non-null  float64
 74  st1038    14976 non-null  float64
 75  st1054    14976 non-null  float64
 76  st1054.1  13880 non-null  float64
 77  st1055    14976 non-null  float64
 78  st1057    14976 non-null  float64
 79  st1079    14976 non-null  float64
dtypes: float64(79), object(1)
memory usage: 9.1+ MB

In [32]:
ppt.head()

,Date,st601,st604,st605,st606,st607,st608,st609,st610,st612,...,st1002,st1004,st1005,st1007,st1038,st1054,st1054.1,st1055,st1057,st1079
0,1/1/1980,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
1,1/2/1980,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
2,1/3/1980,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0
3,1/4/1980,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0
4,1/5/1980,0.0,0.0,13.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0

In [34]:
# Create the list of column names you want (e.g., 'st601', 'st604', etc.)
filtered_columns = [f"st{index}" for index in index_no_values]

# Select only the filtered columns (plus the 'Date' column if needed)
df_filtered = ppt[['Date'] + filtered_columns] if 'Date' in ppt.columns else ppt[filtered_columns]
df_filtered.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14976 entries, 0 to 14975
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    14976 non-null  object
 1   st601   14976 non-null  float64
 2   st604   14976 non-null  float64
 3   st605   14976 non-null  float64
 4   st606   14976 non-null  float64
 5   st715   14976 non-null  float64
 6   st805   14976 non-null  float64
 7   st810   14976 non-null  float64
 8   st814   14976 non-null  float64
dtypes: float64(8), object(1)
memory usage: 1.0+ MB

In [35]:
df_filtered.head()

       Date  st601  st604  st605  st606  st715  st805  st810  st814
0  1/1/1980    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
1  1/2/1980    0.0    0.0    0.0    0.0    2.5    0.0    0.0    0.0
2  1/3/1980    0.0    0.0    0.0    0.0    0.0    0.3    0.0    0.0
3  1/4/1980    0.0    0.0    0.0    0.0    0.0    5.4    0.0    0.0
4  1/5/1980    0.0    0.0   13.0    0.0    0.0    1.0    0.0    0.0

In [46]:
ppt_filtered = df_filtered
ppt_filtered.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14976 entries, 0 to 14975
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    14976 non-null  object
 1   st601   14976 non-null  float64
 2   st604   14976 non-null  float64
 3   st605   14976 non-null  float64
 4   st606   14976 non-null  float64
 5   st715   14976 non-null  float64
 6   st805   14976 non-null  float64
 7   st810   14976 non-null  float64
 8   st814   14976 non-null  float64
dtypes: float64(8), object(1)
memory usage: 1.0+ MB

In [41]:
static_data.head()

    Index_No_   Latitude  Longitude  Elevation
0         601  28.783333  83.716667       2744
1         604  28.750000  83.700000       2566
2         605  28.266667  83.600000        984
3         606  28.483333  83.650000       1243
26        715  27.933333  83.150000       1760

In [47]:
ppt_filtered.head()

       Date  st601  st604  st605  st606  st715  st805  st810  st814
0  1/1/1980    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
1  1/2/1980    0.0    0.0    0.0    0.0    2.5    0.0    0.0    0.0
2  1/3/1980    0.0    0.0    0.0    0.0    0.0    0.3    0.0    0.0
3  1/4/1980    0.0    0.0    0.0    0.0    0.0    5.4    0.0    0.0
4  1/5/1980    0.0    0.0   13.0    0.0    0.0    1.0    0.0    0.0

In [48]:
ppt_filtered.columns = ppt_filtered.columns.str.replace('st', '')
ppt_filtered.head()

       Date  601  604   605  606  715  805  810  814
0  1/1/1980  0.0  0.0   0.0  0.0  0.0  0.0  0.0  0.0
1  1/2/1980  0.0  0.0   0.0  0.0  2.5  0.0  0.0  0.0
2  1/3/1980  0.0  0.0   0.0  0.0  0.0  0.3  0.0  0.0
3  1/4/1980  0.0  0.0   0.0  0.0  0.0  5.4  0.0  0.0
4  1/5/1980  0.0  0.0  13.0  0.0  0.0  1.0  0.0  0.0

In [49]:
t_filtered.columns = t_filtered.columns.str.replace('ST_', '')
t_filtered.head()

,Date,601_tmax,601_tmin,604_tmax,604_tmin,605_tmax,605_tmin,715_tmax,715_tmin,805_tmax,805_tmin,810_tmax,810_tmin,814_tmax,814_tmin
0,1/1/1980,11.31,-1.95,9.2,-3.0,13.00,5.6,14.0,4.3,19.0,6.02,16.0,8.4,13.0,4.0
1,1/2/1980,11.39,-1.74,9.2,-2.0,19.00,7.8,11.7,4.0,18.6,5.40,16.0,9.0,11.2,4.9
2,1/3/1980,11.54,-2.21,7.8,-5.0,19.80,5.4,11.4,5.2,20.4,5.00,18.4,10.0,12.9,4.0
3,1/4/1980,11.45,-2.51,8.3,-5.0,19.60,5.0,12.5,3.3,18.8,6.20,20.2,9.0,10.9,3.5
4,1/5/1980,10.96,-2.32,10.2,-4.2,19.40,4.6,12.8,3.6,20.0,4.80,19.0,7.0,11.5,3.0

In [50]:
# Merging the two DataFrames on 'Date'
merged_df = pd.merge(ppt_filtered, t_filtered, on='Date', how='inner')
merged_df.head()

,Date,601,604,605,606,715,805,810,814,601_tmax,...,605_tmax,605_tmin,715_tmax,715_tmin,805_tmax,805_tmin,810_tmax,810_tmin,814_tmax,814_tmin
0,1/1/1980,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11.31,...,13.00,5.6,14.0,4.3,19.0,6.02,16.0,8.4,13.0,4.0
1,1/2/1980,0.0,0.0,0.0,0.0,2.5,0.0,0.0,0.0,11.39,...,19.00,7.8,11.7,4.0,18.6,5.40,16.0,9.0,11.2,4.9
2,1/3/1980,0.0,0.0,0.0,0.0,0.0,0.3,0.0,0.0,11.54,...,19.80,5.4,11.4,5.2,20.4,5.00,18.4,10.0,12.9,4.0
3,1/4/1980,0.0,0.0,0.0,0.0,0.0,5.4,0.0,0.0,11.45,...,19.60,5.0,12.5,3.3,18.8,6.20,20.2,9.0,10.9,3.5
4,1/5/1980,0.0,0.0,13.0,0.0,0.0,1.0,0.0,0.0,10.96,...,19.40,4.6,12.8,3.6,20.0,4.80,19.0,7.0,11.5,3.0

In [51]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14976 entries, 0 to 14975
Data columns (total 23 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      14976 non-null  object
 1   601       14976 non-null  float64
 2   604       14976 non-null  float64
 3   605       14976 non-null  float64
 4   606       14976 non-null  float64
 5   715       14976 non-null  float64
 6   805       14976 non-null  float64
 7   810       14976 non-null  float64
 8   814       14976 non-null  float64
 9   601_tmax  14976 non-null  float64
 10  601_tmin  14976 non-null  float64
 11  604_tmax  14976 non-null  float64
 12  604_tmin  14976 non-null  float64
 13  605_tmax  14976 non-null  object
 14  605_tmin  14976 non-null  float64
 15  715_tmax  14976 non-null  float64
 16  715_tmin  14976 non-null  float64
 17  805_tmax  14976 non-null  float64
 18  805_tmin  14976 non-null  float64
 19  810_tmax  14976 non-null  float64
 20  810_tmin  14976 non-null  float64
 21  814_tmax  14976 non-null  float64
 22  814_tmin  14976 non-null  float64
dtypes: float64(21), object(2)
memory usage: 2.6+ MB

In [52]:
# Rename columns to include '_ppt' suffix for ppt columns
merged_df.rename(columns=lambda x: x + '_ppt' if x in ['601', '604', '605', '606', '715', '805', '810', '814'] else x, inplace=True)

# Create a list for the new column order
new_order = [
    'Date', 
    '601_ppt', '601_tmax', '601_tmin',
    '604_ppt', '604_tmax', '604_tmin',
    '605_ppt', '605_tmax', '605_tmin',
    '606_ppt',
    '715_ppt', '715_tmax', '715_tmin',
    '805_ppt', '805_tmax', '805_tmin',
    '810_ppt', '810_tmax', '810_tmin',
    '814_ppt', '814_tmax', '814_tmin'
]

# Reindex the DataFrame to the new column order
df = merged_df.reindex(columns=new_order)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14976 entries, 0 to 14975
Data columns (total 23 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      14976 non-null  object
 1   601_ppt   14976 non-null  float64
 2   601_tmax  14976 non-null  float64
 3   601_tmin  14976 non-null  float64
 4   604_ppt   14976 non-null  float64
 5   604_tmax  14976 non-null  float64
 6   604_tmin  14976 non-null  float64
 7   605_ppt   14976 non-null  float64
 8   605_tmax  14976 non-null  object
 9   605_tmin  14976 non-null  float64
 10  606_ppt   14976 non-null  float64
 11  715_ppt   14976 non-null  float64
 12  715_tmax  14976 non-null  float64
 13  715_tmin  14976 non-null  float64
 14  805_ppt   14976 non-null  float64
 15  805_tmax  14976 non-null  float64
 16  805_tmin  14976 non-null  float64
 17  810_ppt   14976 non-null  float64
 18  810_tmax  14976 non-null  float64
 19  810_tmin  14976 non-null  float64
 20  814_ppt   14976 non-null  float64
 21  814_tmax  14976 non-null  float64
 22  814_tmin  14976 non-null  float64
dtypes: float64(21), object(2)
memory usage: 2.6+ MB

In [53]:
time_series_data = df
time_series_data.to_csv('time_series_data.csv')

In [2]:
import pandas as pd
parameters = pd.read_excel('parameter_each_site.xlsx')
parameters.head()

,Unnamed: 0,Parameter Name,Suggested Range,Unnamed: 3,Kaligandaki,Unnamed: 5,Unnamed: 6,Unnamed: 7,Seti Gandaki,Unnamed: 9,Marshyangdi,Unnamed: 11,Budhigandaki,Unnamed: 13,Trishuli,Unnamed: 15,Unnamed: 16,Unnamed: 17,Narayani
0,NaN,NaN,NaN,NaN,Q404.7,Q419.1,Q420,NaN,Q430.5,NaN,Q439.7,NaN,Q445,NaN,Q447,Q448,Q449.91,NaN,Q450
1,NaN,CN2,35 - 98,NaN,0.136645,0.09,0.09,NaN,-0.187227,NaN,0.315746,NaN,0.079112,NaN,0.086917,-0.048375,0.11,NaN,-0.200551
2,NaN,PLAPS,-1000 - 1000,NaN,35.587502,47.48,47.48,NaN,-3.384827,NaN,109.132935,NaN,219.666702,NaN,300,16.275,38.200001,NaN,94.12
3,NaN,TLAPS,-10 - 10,NaN,-5.6075,-6.614,-6.614,NaN,-5.40834,NaN,-3.151747,NaN,-7.22904,NaN,-6.676458,-7.053229,-7.43,NaN,-0.8875
4,NaN,SFTMP,-20 - 20,NaN,-,-,-5.290562,NaN,-,NaN,-5.290562,NaN,-5.290562,NaN,-5.290562,-,-,NaN,-

In [3]:
parameters.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        0 non-null      float64
 1   Parameter Name    29 non-null     object
 2   Suggested Range   29 non-null     object
 3   Unnamed: 3        0 non-null      float64
 4   Kaligandaki       30 non-null     object
 5   Unnamed: 5        30 non-null     object
 6   Unnamed: 6        30 non-null     object
 7   Unnamed: 7        0 non-null      float64
 8   Seti Gandaki      30 non-null     object
 9   Unnamed: 9        0 non-null      float64
 10  Marshyangdi       30 non-null     object
 11  Unnamed: 11       0 non-null      float64
 12  Budhigandaki      30 non-null     object
 13  Unnamed: 13       0 non-null      float64
 14  Trishuli          30 non-null     object
 15  Unnamed: 15       30 non-null     object
 16  Unnamed: 16       30 non-null     object
 17  Unnamed: 17       0 non-null      float64
 18  Narayani          30 non-null     object
dtypes: float64(7), object(12)
memory usage: 4.6+ KB

In [5]:
parameters['Q420'] = parameters['Unnamed: 6'][1:]
parameters['Q420']

0           NaN
1          0.09
2         47.48
3        -6.614
4     -5.290562
5      -3.52523
6      4.040531
7      4.995668
8      0.100382
9       2.64695
10      -0.0615
11      -0.0297
12      -0.0945
13      -0.0819
14       0.0716
15         24.5
16        0.029
17        0.387
18        17.29
19      0.38779
20       0.6921
21     0.020644
22        149.3
23         3299
24        121.5
25      0.04934
26         1742
27    47.474998
28      0.78519
29      0.09145
Name: Q420, dtype: object

In [ ]:
parameters['Q404.7'] = parameters['Kaligandaki '][1:]
parameters['Q404.7']

In [6]:
parameters.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        0 non-null      float64
 1   Parameter Name    29 non-null     object
 2   Suggested Range   29 non-null     object
 3   Unnamed: 3        0 non-null      float64
 4   Kaligandaki       30 non-null     object
 5   Unnamed: 5        30 non-null     object
 6   Unnamed: 6        30 non-null     object
 7   Unnamed: 7        0 non-null      float64
 8   Seti Gandaki      30 non-null     object
 9   Unnamed: 9        0 non-null      float64
 10  Marshyangdi       30 non-null     object
 11  Unnamed: 11       0 non-null      float64
 12  Budhigandaki      30 non-null     object
 13  Unnamed: 13       0 non-null      float64
 14  Trishuli          30 non-null     object
 15  Unnamed: 15       30 non-null     object
 16  Unnamed: 16       30 non-null     object
 17  Unnamed: 17       0 non-null      float64
 18  Narayani          30 non-null     object
 19  Q404.7            29 non-null     object
 20  Q420              29 non-null     object
dtypes: float64(7), object(14)
memory usage: 5.1+ KB

In [12]:
df = parameters
df.columns = df.columns.str.strip()

# Select only the desired columns
filtered_df = df[['Parameter Name', 'Suggested Range', 'Q420']]

# Resetting the index (optional)
filtered_df.reset_index(drop=True, inplace=True)

filtered_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Parameter Name   29 non-null     object
 1   Suggested Range  29 non-null     object
 2   Q420             29 non-null     object
dtypes: object(3)
memory usage: 852.0+ bytes

In [13]:
parameters = filtered_df
parameters.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Parameter Name   29 non-null     object
 1   Suggested Range  29 non-null     object
 2   Q420             29 non-null     object
dtypes: object(3)
memory usage: 852.0+ bytes

In [14]:
parameters.head()

  Parameter Name Suggested Range      Q420
0            NaN             NaN       NaN
1            CN2         35 - 98      0.09
2          PLAPS   -1000 - 1000      47.48
3          TLAPS        -10 - 10    -6.614
4          SFTMP        -20 - 20 -5.290562

In [15]:
parameters = parameters.drop(index=0).reset_index(drop=True)
parameters.head()

  Parameter Name Suggested Range      Q420
0            CN2         35 - 98      0.09
1          PLAPS   -1000 - 1000      47.48
2          TLAPS        -10 - 10    -6.614
3          SFTMP        -20 - 20 -5.290562
4          SMTMP        -20 - 20  -3.52523

In [16]:
parameters.to_csv('parameters.csv')

In [18]:
runoff_data = pd.read_csv('runoff.csv')
runoff_data.head()

  Unnamed: 0                   Unnamed: 1
0       Date  Kaligandaki Kotagaun ST-420
1   1/1/1980                          128
2   1/2/1980                          118
3   1/3/1980                          114
4   1/4/1980                          111

In [19]:
runoff_data.columns = runoff_data.iloc[0]
runoff_data = runoff_data[1:]  # Drop the first row

# Reset the index (optional)
runoff_data.reset_index(drop=True, inplace=True)

# Display the modified DataFrame
print(runoff_data)

0            Date Kaligandaki Kotagaun ST-420
0        1/1/1980                         128
1        1/2/1980                         118
2        1/3/1980                         114
3        1/4/1980                         111
4        1/5/1980                         111
...           ...                         ...
14605  12/27/2019                         146
14606  12/28/2019                         142
14607  12/29/2019                         156
14608  12/30/2019                         147
14609  12/31/2019                         167

[14610 rows x 2 columns]

In [20]:
runoff_data.head()

0      Date Kaligandaki Kotagaun ST-420
0  1/1/1980                         128
1  1/2/1980                         118
2  1/3/1980                         114
3  1/4/1980                         111
4  1/5/1980                         111

In [22]:
runoff_data.rename(columns={'Kaligandaki Kotagaun ST-420':'runoff_value'}, inplace=True)
runoff_data.head()

0      Date runoff_value
0  1/1/1980          128
1  1/2/1980          118
2  1/3/1980          114
3  1/4/1980          111
4  1/5/1980          111

In [24]:
runoff_data.to_csv('runoff_data.csv')

In [3]:
import pandas as pd

In [11]:
runoff_data = pd.read_csv('runoff_data.csv')
runoff_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14610 entries, 0 to 14609
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    14610 non-null  int64
 1   Date          14610 non-null  object
 2   runoff_value  14157 non-null  float64
dtypes: float64(1), int64(1), object(1)
memory usage: 342.6+ KB

In [12]:
runoff_data['runoff_value'].fillna(runoff_data['runoff_value'].mean(), inplace=True)
runoff_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14610 entries, 0 to 14609
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    14610 non-null  int64
 1   Date          14610 non-null  object
 2   runoff_value  14610 non-null  float64
dtypes: float64(1), int64(1), object(1)
memory usage: 342.6+ KB

C:\Users\Gunjan M\AppData\Local\Temp\ipykernel_13504\3754413953.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  runoff_data['runoff_value'].fillna(runoff_data['runoff_value'].mean(), inplace=True)

In [13]:
runoff_data.to_csv('runoff_data.csv')

In [5]:
time_series_data = pd.read_csv('time_series_data.csv')
time_series_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14976 entries, 0 to 14975
Data columns (total 24 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  14976 non-null  int64
 1   Date        14976 non-null  object
 2   601_ppt     14976 non-null  float64
 3   601_tmax    14976 non-null  float64
 4   601_tmin    14976 non-null  float64
 5   604_ppt     14976 non-null  float64
 6   604_tmax    14976 non-null  float64
 7   604_tmin    14976 non-null  float64
 8   605_ppt     14976 non-null  float64
 9   605_tmax    14976 non-null  object
 10  605_tmin    14976 non-null  float64
 11  606_ppt     14976 non-null  float64
 12  715_ppt     14976 non-null  float64
 13  715_tmax    14976 non-null  float64
 14  715_tmin    14976 non-null  float64
 15  805_ppt     14976 non-null  float64
 16  805_tmax    14976 non-null  float64
 17  805_tmin    14976 non-null  float64
 18  810_ppt     14976 non-null  float64
 19  810_tmax    14976 non-null  float64
 20  810_tmin    14976 non-null  float64
 21  814_ppt     14976 non-null  float64
 22  814_tmax    14976 non-null  float64
 23  814_tmin    14976 non-null  float64
dtypes: float64(21), int64(1), object(2)
memory usage: 2.7+ MB