In [1]:
import pandas as pd
runoff_data = pd.read_csv('runoff_data.csv')

In [2]:
runoff_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14610 entries, 0 to 14609
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0.1  14610 non-null  int64
 1   Unnamed: 0    14610 non-null  int64
 2   Date          14610 non-null  object
 3   runoff_value  14610 non-null  float64
dtypes: float64(1), int64(2), object(1)
memory usage: 456.7+ KB

In [3]:
runoff_data.head()

   Unnamed: 0.1  Unnamed: 0      Date  runoff_value
0             0           0  1/1/1980         128.0
1             1           1  1/2/1980         118.0
2             2           2  1/3/1980         114.0
3             3           3  1/4/1980         111.0
4             4           4  1/5/1980         111.0

In [4]:
runoff_data = runoff_data.loc[:, ~runoff_data.columns.str.contains('^Unnamed')]
runoff_data.head()

       Date  runoff_value
0  1/1/1980         128.0
1  1/2/1980         118.0
2  1/3/1980         114.0
3  1/4/1980         111.0
4  1/5/1980         111.0

In [5]:
runoff_data.to_csv('runoff_data.csv')

In [6]:
time_series_data = pd.read_csv('time_series_data.csv')
time_series_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14976 entries, 0 to 14975
Data columns (total 24 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  14976 non-null  int64
 1   Date        14976 non-null  object
 2   601_ppt     14976 non-null  float64
 3   601_tmax    14976 non-null  float64
 4   601_tmin    14976 non-null  float64
 5   604_ppt     14976 non-null  float64
 6   604_tmax    14976 non-null  float64
 7   604_tmin    14976 non-null  float64
 8   605_ppt     14976 non-null  float64
 9   605_tmax    14976 non-null  object
 10  605_tmin    14976 non-null  float64
 11  606_ppt     14976 non-null  float64
 12  715_ppt     14976 non-null  float64
 13  715_tmax    14976 non-null  float64
 14  715_tmin    14976 non-null  float64
 15  805_ppt     14976 non-null  float64
 16  805_tmax    14976 non-null  float64
 17  805_tmin    14976 non-null  float64
 18  810_ppt     14976 non-null  float64
 19  810_tmax    14976 non-null  float64
 20  810_tmin    14976 non-null  float64
 21  814_ppt     14976 non-null  float64
 22  814_tmax    14976 non-null  float64
 23  814_tmin    14976 non-null  float64
dtypes: float64(21), int64(1), object(2)
memory usage: 2.7+ MB

In [7]:
# Merge the datasets on Date
combined_data = pd.merge(runoff_data[['Date', 'runoff_value']], time_series_data, on='Date', how='inner')
combined_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14610 entries, 0 to 14609
Data columns (total 25 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          14610 non-null  object
 1   runoff_value  14610 non-null  float64
 2   Unnamed: 0    14610 non-null  int64
 3   601_ppt       14610 non-null  float64
 4   601_tmax      14610 non-null  float64
 5   601_tmin      14610 non-null  float64
 6   604_ppt       14610 non-null  float64
 7   604_tmax      14610 non-null  float64
 8   604_tmin      14610 non-null  float64
 9   605_ppt       14610 non-null  float64
 10  605_tmax      14610 non-null  object
 11  605_tmin      14610 non-null  float64
 12  606_ppt       14610 non-null  float64
 13  715_ppt       14610 non-null  float64
 14  715_tmax      14610 non-null  float64
 15  715_tmin      14610 non-null  float64
 16  805_ppt       14610 non-null  float64
 17  805_tmax      14610 non-null  float64
 18  805_tmin      14610 non-null  float64
 19  810_ppt       14610 non-null  float64
 20  810_tmax      14610 non-null  float64
 21  810_tmin      14610 non-null  float64
 22  814_ppt       14610 non-null  float64
 23  814_tmax      14610 non-null  float64
 24  814_tmin      14610 non-null  float64
dtypes: float64(22), int64(1), object(2)
memory usage: 2.8+ MB

In [8]:
combined_data.head()

,Date,runoff_value,Unnamed: 0,601_ppt,601_tmax,601_tmin,604_ppt,604_tmax,604_tmin,605_ppt,...,715_tmin,805_ppt,805_tmax,805_tmin,810_ppt,810_tmax,810_tmin,814_ppt,814_tmax,814_tmin
0,1/1/1980,128.0,0,0.0,11.31,-1.95,0.0,9.2,-3.0,0.0,...,4.3,0.0,19.0,6.02,0.0,16.0,8.4,0.0,13.0,4.0
1,1/2/1980,118.0,1,0.0,11.39,-1.74,0.0,9.2,-2.0,0.0,...,4.0,0.0,18.6,5.40,0.0,16.0,9.0,0.0,11.2,4.9
2,1/3/1980,114.0,2,0.0,11.54,-2.21,0.0,7.8,-5.0,0.0,...,5.2,0.3,20.4,5.00,0.0,18.4,10.0,0.0,12.9,4.0
3,1/4/1980,111.0,3,0.0,11.45,-2.51,0.0,8.3,-5.0,0.0,...,3.3,5.4,18.8,6.20,0.0,20.2,9.0,0.0,10.9,3.5
4,1/5/1980,111.0,4,0.0,10.96,-2.32,0.0,10.2,-4.2,13.0,...,3.6,1.0,20.0,4.80,0.0,19.0,7.0,0.0,11.5,3.0

In [9]:
combined_data = combined_data.loc[:, ~combined_data.columns.str.contains('^Unnamed')]
combined_data.head()

,Date,runoff_value,601_ppt,601_tmax,601_tmin,604_ppt,604_tmax,604_tmin,605_ppt,605_tmax,...,715_tmin,805_ppt,805_tmax,805_tmin,810_ppt,810_tmax,810_tmin,814_ppt,814_tmax,814_tmin
0,1/1/1980,128.0,0.0,11.31,-1.95,0.0,9.2,-3.0,0.0,13.00,...,4.3,0.0,19.0,6.02,0.0,16.0,8.4,0.0,13.0,4.0
1,1/2/1980,118.0,0.0,11.39,-1.74,0.0,9.2,-2.0,0.0,19.00,...,4.0,0.0,18.6,5.40,0.0,16.0,9.0,0.0,11.2,4.9
2,1/3/1980,114.0,0.0,11.54,-2.21,0.0,7.8,-5.0,0.0,19.80,...,5.2,0.3,20.4,5.00,0.0,18.4,10.0,0.0,12.9,4.0
3,1/4/1980,111.0,0.0,11.45,-2.51,0.0,8.3,-5.0,0.0,19.60,...,3.3,5.4,18.8,6.20,0.0,20.2,9.0,0.0,10.9,3.5
4,1/5/1980,111.0,0.0,10.96,-2.32,0.0,10.2,-4.2,13.0,19.40,...,3.6,1.0,20.0,4.80,0.0,19.0,7.0,0.0,11.5,3.0

In [10]:
combined_data.to_csv('final_data.csv')

In [11]:
combined_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14610 entries, 0 to 14609
Data columns (total 24 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          14610 non-null  object
 1   runoff_value  14610 non-null  float64
 2   601_ppt       14610 non-null  float64
 3   601_tmax      14610 non-null  float64
 4   601_tmin      14610 non-null  float64
 5   604_ppt       14610 non-null  float64
 6   604_tmax      14610 non-null  float64
 7   604_tmin      14610 non-null  float64
 8   605_ppt       14610 non-null  float64
 9   605_tmax      14610 non-null  object
 10  605_tmin      14610 non-null  float64
 11  606_ppt       14610 non-null  float64
 12  715_ppt       14610 non-null  float64
 13  715_tmax      14610 non-null  float64
 14  715_tmin      14610 non-null  float64
 15  805_ppt       14610 non-null  float64
 16  805_tmax      14610 non-null  float64
 17  805_tmin      14610 non-null  float64
 18  810_ppt       14610 non-null  float64
 19  810_tmax      14610 non-null  float64
 20  810_tmin      14610 non-null  float64
 21  814_ppt       14610 non-null  float64
 22  814_tmax      14610 non-null  float64
 23  814_tmin      14610 non-null  float64
dtypes: float64(22), object(2)
memory usage: 2.7+ MB

In [13]:
combined_data.replace('#VALUE!', pd.NA, inplace=True)
combined_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14610 entries, 0 to 14609
Data columns (total 24 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          14610 non-null  datetime64[ns]
 1   runoff_value  14610 non-null  float64
 2   601_ppt       14610 non-null  float64
 3   601_tmax      14610 non-null  float64
 4   601_tmin      14610 non-null  float64
 5   604_ppt       14610 non-null  float64
 6   604_tmax      14610 non-null  float64
 7   604_tmin      14610 non-null  float64
 8   605_ppt       14610 non-null  float64
 9   605_tmax      14609 non-null  object
 10  605_tmin      14610 non-null  float64
 11  606_ppt       14610 non-null  float64
 12  715_ppt       14610 non-null  float64
 13  715_tmax      14610 non-null  float64
 14  715_tmin      14610 non-null  float64
 15  805_ppt       14610 non-null  float64
 16  805_tmax      14610 non-null  float64
 17  805_tmin      14610 non-null  float64
 18  810_ppt       14610 non-null  float64
 19  810_tmax      14610 non-null  float64
 20  810_tmin      14610 non-null  float64
 21  814_ppt       14610 non-null  float64
 22  814_tmax      14610 non-null  float64
 23  814_tmin      14610 non-null  float64
dtypes: datetime64[ns](1), float64(22), object(1)
memory usage: 2.7+ MB

In [17]:
import numpy as np
# Replace specific non-numeric values like '#VALUE!' with NaN
combined_data['605_tmax'].replace('#VALUE!', np.nan, inplace=True)

# Convert to numeric with errors coerced to NaN
combined_data['605_tmax'] = pd.to_numeric(combined_data['605_tmax'], errors='coerce')

# Now fill NaN values with the column mean
combined_data['605_tmax'].fillna(combined_data['605_tmax'].mean(), inplace=True)

# Confirm the changes
print(combined_data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14610 entries, 0 to 14609
Data columns (total 24 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          14610 non-null  datetime64[ns]
 1   runoff_value  14610 non-null  float64
 2   601_ppt       14610 non-null  float64
 3   601_tmax      14610 non-null  float64
 4   601_tmin      14610 non-null  float64
 5   604_ppt       14610 non-null  float64
 6   604_tmax      14610 non-null  float64
 7   604_tmin      14610 non-null  float64
 8   605_ppt       14610 non-null  float64
 9   605_tmax      14610 non-null  float64
 10  605_tmin      14610 non-null  float64
 11  606_ppt       14610 non-null  float64
 12  715_ppt       14610 non-null  float64
 13  715_tmax      14610 non-null  float64
 14  715_tmin      14610 non-null  float64
 15  805_ppt       14610 non-null  float64
 16  805_tmax      14610 non-null  float64
 17  805_tmin      14610 non-null  float64
 18  810_ppt       14610 non-null  float64
 19  810_tmax      14610 non-null  float64
 20  810_tmin      14610 non-null  float64
 21  814_ppt       14610 non-null  float64
 22  814_tmax      14610 non-null  float64
 23  814_tmin      14610 non-null  float64
dtypes: datetime64[ns](1), float64(23)
memory usage: 2.7 MB
None

C:\Users\Gunjan M\AppData\Local\Temp\ipykernel_13488\1280822559.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  combined_data['605_tmax'].fillna(combined_data['605_tmax'].mean(), inplace=True)

In [18]:
combined_data.to_csv('final.csv')