In [1]:
import pandas as pd
final_df = pd.read_csv('final.csv')
static_df = pd.read_csv('static_data.csv')
parameters_df = pd.read_csv('parameters.csv')

In [2]:
print(final_df.info())
print(static_df.info())
print(parameters_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14610 entries, 0 to 14609
Data columns (total 25 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    14610 non-null  int64
 1   Date          14610 non-null  object
 2   runoff_value  14610 non-null  float64
 3   601_ppt       14610 non-null  float64
 4   601_tmax      14610 non-null  float64
 5   601_tmin      14610 non-null  float64
 6   604_ppt       14610 non-null  float64
 7   604_tmax      14610 non-null  float64
 8   604_tmin      14610 non-null  float64
 9   605_ppt       14610 non-null  float64
 10  605_tmax      14610 non-null  float64
 11  605_tmin      14610 non-null  float64
 12  606_ppt       14610 non-null  float64
 13  715_ppt       14610 non-null  float64
 14  715_tmax      14610 non-null  float64
 15  715_tmin      14610 non-null  float64
 16  805_ppt       14610 non-null  float64
 17  805_tmax      14610 non-null  float64
 18  805_tmin      14610 non-null  float64
 19  810_ppt       14610 non-null  float64
 20  810_tmax      14610 non-null  float64
 21  810_tmin      14610 non-null  float64
 22  814_ppt       14610 non-null  float64
 23  814_tmax      14610 non-null  float64
 24  814_tmin      14610 non-null  float64
dtypes: float64(23), int64(1), object(1)
memory usage: 2.8+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  8 non-null      int64
 1   Index_No_   8 non-null      int64
 2   Latitude    8 non-null      float64
 3   Longitude   8 non-null      float64
 4   Elevation   8 non-null      int64
dtypes: float64(2), int64(3)
memory usage: 452.0 bytes
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       29 non-null     int64
 1   Parameter Name   29 non-null     object
 2   Suggested Range  29 non-null     object
 3   Q420             29 non-null     float64
dtypes: float64(1), int64(1), object(2)
memory usage: 1.0+ KB
None

In [3]:
final_df.head()

,Unnamed: 0,Date,runoff_value,601_ppt,601_tmax,601_tmin,604_ppt,604_tmax,604_tmin,605_ppt,...,715_tmin,805_ppt,805_tmax,805_tmin,810_ppt,810_tmax,810_tmin,814_ppt,814_tmax,814_tmin
0,0,1980-01-01,128.0,0.0,11.31,-1.95,0.0,9.2,-3.0,0.0,...,4.3,0.0,19.0,6.02,0.0,16.0,8.4,0.0,13.0,4.0
1,1,1980-01-02,118.0,0.0,11.39,-1.74,0.0,9.2,-2.0,0.0,...,4.0,0.0,18.6,5.40,0.0,16.0,9.0,0.0,11.2,4.9
2,2,1980-01-03,114.0,0.0,11.54,-2.21,0.0,7.8,-5.0,0.0,...,5.2,0.3,20.4,5.00,0.0,18.4,10.0,0.0,12.9,4.0
3,3,1980-01-04,111.0,0.0,11.45,-2.51,0.0,8.3,-5.0,0.0,...,3.3,5.4,18.8,6.20,0.0,20.2,9.0,0.0,10.9,3.5
4,4,1980-01-05,111.0,0.0,10.96,-2.32,0.0,10.2,-4.2,13.0,...,3.6,1.0,20.0,4.80,0.0,19.0,7.0,0.0,11.5,3.0

In [6]:
final_df.drop(columns=['Unnamed: 0'], inplace=True)

In [8]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14610 entries, 0 to 14609
Data columns (total 24 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          14610 non-null  object
 1   runoff_value  14610 non-null  float64
 2   601_ppt       14610 non-null  float64
 3   601_tmax      14610 non-null  float64
 4   601_tmin      14610 non-null  float64
 5   604_ppt       14610 non-null  float64
 6   604_tmax      14610 non-null  float64
 7   604_tmin      14610 non-null  float64
 8   605_ppt       14610 non-null  float64
 9   605_tmax      14610 non-null  float64
 10  605_tmin      14610 non-null  float64
 11  606_ppt       14610 non-null  float64
 12  715_ppt       14610 non-null  float64
 13  715_tmax      14610 non-null  float64
 14  715_tmin      14610 non-null  float64
 15  805_ppt       14610 non-null  float64
 16  805_tmax      14610 non-null  float64
 17  805_tmin      14610 non-null  float64
 18  810_ppt       14610 non-null  float64
 19  810_tmax      14610 non-null  float64
 20  810_tmin      14610 non-null  float64
 21  814_ppt       14610 non-null  float64
 22  814_tmax      14610 non-null  float64
 23  814_tmin      14610 non-null  float64
dtypes: float64(23), object(1)
memory usage: 2.7+ MB

In [9]:
final_df.head()

,Date,runoff_value,601_ppt,601_tmax,601_tmin,604_ppt,604_tmax,604_tmin,605_ppt,605_tmax,...,715_tmin,805_ppt,805_tmax,805_tmin,810_ppt,810_tmax,810_tmin,814_ppt,814_tmax,814_tmin
0,1980-01-01,128.0,0.0,11.31,-1.95,0.0,9.2,-3.0,0.0,13.0,...,4.3,0.0,19.0,6.02,0.0,16.0,8.4,0.0,13.0,4.0
1,1980-01-02,118.0,0.0,11.39,-1.74,0.0,9.2,-2.0,0.0,19.0,...,4.0,0.0,18.6,5.40,0.0,16.0,9.0,0.0,11.2,4.9
2,1980-01-03,114.0,0.0,11.54,-2.21,0.0,7.8,-5.0,0.0,19.8,...,5.2,0.3,20.4,5.00,0.0,18.4,10.0,0.0,12.9,4.0
3,1980-01-04,111.0,0.0,11.45,-2.51,0.0,8.3,-5.0,0.0,19.6,...,3.3,5.4,18.8,6.20,0.0,20.2,9.0,0.0,10.9,3.5
4,1980-01-05,111.0,0.0,10.96,-2.32,0.0,10.2,-4.2,13.0,19.4,...,3.6,1.0,20.0,4.80,0.0,19.0,7.0,0.0,11.5,3.0

In [10]:
# Step 1: Convert Date to datetime
final_df['Date'] = pd.to_datetime(final_df['Date'])

# Step 2: Handle Missing Values
# Check for missing values
missing_values = final_df.isnull().sum()
print("Missing values per column before handling:\n", missing_values)

Missing values per column before handling:
 Date            0
runoff_value    0
601_ppt         0
601_tmax        0
601_tmin        0
604_ppt         0
604_tmax        0
604_tmin        0
605_ppt         0
605_tmax        0
605_tmin        0
606_ppt         0
715_ppt         0
715_tmax        0
715_tmin        0
805_ppt         0
805_tmax        0
805_tmin        0
810_ppt         0
810_tmax        0
810_tmin        0
814_ppt         0
814_tmax        0
814_tmin        0
dtype: int64

In [11]:
# Step 3: Create Lag Features
# Create a 1-day lag for runoff value, which can help capture recent runoff patterns
final_df['runoff_lag1'] = final_df['runoff_value'].shift(1)

weather_columns = ['601_ppt', '604_ppt', '605_ppt', '606_ppt', '715_ppt', '805_ppt', '810_ppt', '814_ppt', 
                   '601_tmax', '601_tmin']
# Lag features for precipitation data (adjust as needed based on patterns)
for col in weather_columns:
    final_df[f'{col}_lag1'] = final_df[col].shift(1)

# Drop any rows with NaNs that might have been introduced by lagging
final_df = final_df.dropna()

# Step 4: Add Seasonal Features
final_df['month'] = final_df['Date'].dt.month  # Month can capture seasonality

C:\Users\Gunjan M\AppData\Local\Temp\ipykernel_2988\3436210507.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['month'] = final_df['Date'].dt.month  # Month can capture seasonality

In [12]:
final_df.head()

,Date,runoff_value,601_ppt,601_tmax,601_tmin,604_ppt,604_tmax,604_tmin,605_ppt,605_tmax,...,604_ppt_lag1,605_ppt_lag1,606_ppt_lag1,715_ppt_lag1,805_ppt_lag1,810_ppt_lag1,814_ppt_lag1,601_tmax_lag1,601_tmin_lag1,month
1,1980-01-02,118.0,0.0,11.39,-1.74,0.0,9.2,-2.0,0.0,19.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11.31,-1.95,1
2,1980-01-03,114.0,0.0,11.54,-2.21,0.0,7.8,-5.0,0.0,19.8,...,0.0,0.0,0.0,2.5,0.0,0.0,0.0,11.39,-1.74,1
3,1980-01-04,111.0,0.0,11.45,-2.51,0.0,8.3,-5.0,0.0,19.6,...,0.0,0.0,0.0,0.0,0.3,0.0,0.0,11.54,-2.21,1
4,1980-01-05,111.0,0.0,10.96,-2.32,0.0,10.2,-4.2,13.0,19.4,...,0.0,0.0,0.0,0.0,5.4,0.0,0.0,11.45,-2.51,1
5,1980-01-06,108.0,0.0,10.92,-2.04,0.0,9.0,-3.5,0.0,19.4,...,0.0,13.0,0.0,0.0,1.0,0.0,0.0,10.96,-2.32,1

In [14]:
final_df['month'].nunique()

12

In [18]:
import matplotlib.pyplot as plt
import seaborn as sns

# Extract year and month for grouping
final_df['Year'] = final_df['Date'].dt.year
final_df['Month'] = final_df['Date'].dt.month

# Month groupings for each subplot
month_groups = [(1, 3), (4, 6), (7, 9), (10, 12)]
titles = ['January - March', 'April - June', 'July - September', 'October - December']

# Generate and save each plot
for i, (start_month, end_month) in enumerate(month_groups):
    plt.figure(figsize=(10, 6))
    
    # Filter data for each set of 3 months
    for month in range(start_month, end_month + 1):
        month_data = final_df[final_df['Month'] == month]
        plt.plot(month_data['Date'], month_data['runoff_value'], label=f'Month {month}', alpha=0.7)
    
    # Set titles and labels
    plt.title(f'Runoff Value Over Time ({titles[i]})')
    plt.xlabel('Date')
    plt.ylabel('Runoff Value')
    plt.legend(title='Month', loc='upper right')
    plt.grid(True)
    
    # Save the figure
    plt.tight_layout()
    plt.savefig(f'runoff_plot_{titles[i].replace(" ", "_")}.png')
    plt.close()  # Close the figure to free memory

print("Plots saved successfully.")

Plots saved successfully.

In [27]:
# Step 1: Reshape final_df to a long format
# Extract the station numbers and variable types
id_vars = ['Date', 'runoff_value']  # Columns to keep in place
value_vars = [col for col in final_df.columns if col not in id_vars]

# Melt the DataFrame to create 'Station' and 'Type' columns
long_df = pd.melt(final_df, id_vars=id_vars, value_vars=value_vars,
                  var_name='Station_Type', value_name='Value')

# Split 'Station_Type' into 'Station' and 'Type'
long_df[['Station', 'Type']] = long_df['Station_Type'].str.extract(r'(\d+)_([a-zA-Z]+)')

# Drop rows where 'Station' is NaN
long_df = long_df.dropna(subset=['Station'])

# Convert 'Station' to integer after handling NaNs
long_df['Station'] = long_df['Station'].astype(int)

# Step 2: Merge with static data on 'Station'
merged_df = pd.merge(long_df, static_df, left_on='Station', right_on='Index_No_', how='left')
merged_df = merged_df.drop(columns='Index_No_')  # Drop redundant column

# Step 3: Optionally add parameter data
# merged_df = merged_df.merge(parameters_df, left_on='Type', right_on='Parameter Name', how='left')

# Save the merged data if necessary
merged_df.to_csv('merged_final_static.csv', index=False)

print("Data merged successfully. Check 'merged_final_static.csv' for the output.")

Data merged successfully. Check 'merged_final_static.csv' for the output.

In [28]:
df = pd.read_csv('merged_final_static.csv')
df.head()

,Date,runoff_value,Station_Type,Value,Station,Type,Unnamed: 0,Latitude,Longitude,Elevation
0,1980-01-02,118.0,601_ppt,0.0,601,ppt,0,28.783333,83.716667,2744
1,1980-01-03,114.0,601_ppt,0.0,601,ppt,0,28.783333,83.716667,2744
2,1980-01-04,111.0,601_ppt,0.0,601,ppt,0,28.783333,83.716667,2744
3,1980-01-05,111.0,601_ppt,0.0,601,ppt,0,28.783333,83.716667,2744
4,1980-01-06,108.0,601_ppt,0.0,601,ppt,0,28.783333,83.716667,2744

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 467488 entries, 0 to 467487
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Date          467488 non-null  object
 1   runoff_value  467488 non-null  float64
 2   Station_Type  467488 non-null  object
 3   Value         467488 non-null  float64
 4   Station       467488 non-null  int64
 5   Type          467488 non-null  object
 6   Unnamed: 0    467488 non-null  int64
 7   Latitude      467488 non-null  float64
 8   Longitude     467488 non-null  float64
 9   Elevation     467488 non-null  int64
dtypes: float64(4), int64(3), object(3)
memory usage: 35.7+ MB

In [30]:
df['Station_Type'].nunique()

32

In [33]:
df.drop(columns=['Unnamed: 0'], inplace=True)
df.head()

,Date,runoff_value,Station_Type,Value,Station,Type,Latitude,Longitude,Elevation
0,1980-01-02,118.0,601_ppt,0.0,601,ppt,28.783333,83.716667,2744
1,1980-01-03,114.0,601_ppt,0.0,601,ppt,28.783333,83.716667,2744
2,1980-01-04,111.0,601_ppt,0.0,601,ppt,28.783333,83.716667,2744
3,1980-01-05,111.0,601_ppt,0.0,601,ppt,28.783333,83.716667,2744
4,1980-01-06,108.0,601_ppt,0.0,601,ppt,28.783333,83.716667,2744

In [34]:
df['Value'].nunique()

6050

In [35]:
df['Value']

0         0.0
1         0.0
2         0.0
3         0.0
4         0.0
         ...
467483   -3.5
467484   -4.5
467485   -3.0
467486   -3.2
467487   -5.7
Name: Value, Length: 467488, dtype: float64

In [37]:
df.to_csv('df.csv')

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 467488 entries, 0 to 467487
Data columns (total 9 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Date          467488 non-null  object
 1   runoff_value  467488 non-null  float64
 2   Station_Type  467488 non-null  object
 3   Value         467488 non-null  float64
 4   Station       467488 non-null  int64
 5   Type          467488 non-null  object
 6   Latitude      467488 non-null  float64
 7   Longitude     467488 non-null  float64
 8   Elevation     467488 non-null  int64
dtypes: float64(4), int64(2), object(3)
memory usage: 32.1+ MB